export const newsData = [
  {
    title: "Tech Giant Releases New AI Model",
    desc: "A major tech company has launched its latest AI model, setting new benchmarks in the industry.",
    pubDate: "2025-02-12",
    pubName: "Tech Times",
    pubLogo: "https://example.com/tech-times-logo.png",
    sentiment: "Positive",
  },
  {
    title: "Stock Market Sees Major Dip",
    desc: "Markets faced a sharp decline today amid concerns over global economic instability.",
    pubDate: "2025-02-12",
    pubName: "Finance Daily",
    pubLogo: "https://example.com/finance-daily-logo.png",
    sentiment: "Neutral",
  },
  {
    title: "Breakthrough in Renewable Energy",
    desc: "Scientists have discovered a new, highly efficient solar panel technology that could revolutionize the industry.",
    pubDate: "2025-02-11",
    pubName: "Green Future",
    pubLogo: "https://example.com/green-future-logo.png",
    sentiment: "Positive",
  },
  {
    title: "New Cybersecurity Threat Detected",
    desc: "A sophisticated cyber attack has been identified, targeting major financial institutions worldwide.",
    pubDate: "2025-02-10",
    pubName: "CyberSec Today",
    pubLogo: "https://example.com/cybersec-today-logo.png",
    sentiment: "Negative",
  },
  {
    title: "Sports Team Wins Championship",
    desc: "After a thrilling final, the underdogs secured a historic victory in the national championship.",
    pubDate: "2025-02-09",
    pubName: "Sports Weekly",
    pubLogo: "https://example.com/sports-weekly-logo.png",
    sentiment: "Positive",
  },
  {
    title: "Stock Market Sees Major Dip",
    desc: "Markets faced a sharp decline today amid concerns over global economic instability.",
    pubDate: "2025-02-12",
    pubName: "Finance Daily",
    pubLogo: "https://example.com/finance-daily-logo.png",
    sentiment: "Neutral",
  },
  {
    title: "Breakthrough in Renewable Energy",
    desc: "Scientists have discovered a new, highly efficient solar panel technology that could revolutionize the industry.",
    pubDate: "2025-02-11",
    pubName: "Green Future",
    pubLogo: "https://example.com/green-future-logo.png",
    sentiment: "Positive",
  },
  {
    title: "New Cybersecurity Threat Detected",
    desc: "A sophisticated cyber attack has been identified, targeting major financial institutions worldwide.",
    pubDate: "2025-02-10",
    pubName: "CyberSec Today",
    pubLogo: "https://example.com/cybersec-today-logo.png",
    sentiment: "Negative",
  },
  {
    title: "Sports Team Wins Championship",
    desc: "After a thrilling final, the underdogs secured a historic victory in the national championship.",
    pubDate: "2025-02-09",
    pubName: "Sports Weekly",
    pubLogo: "https://example.com/sports-weekly-logo.png",
    sentiment: "Positive",
  },
  {
    title: "Stock Market Sees Major Dip",
    desc: "Markets faced a sharp decline today amid concerns over global economic instability.",
    pubDate: "2025-02-12",
    pubName: "Finance Daily",
    pubLogo: "https://example.com/finance-daily-logo.png",
    sentiment: "Neutral",
  },
  {
    title: "Breakthrough in Renewable Energy",
    desc: "Scientists have discovered a new, highly efficient solar panel technology that could revolutionize the industry.",
    pubDate: "2025-02-11",
    pubName: "Green Future",
    pubLogo: "https://example.com/green-future-logo.png",
    sentiment: "Positive",
  },
  {
    title: "New Cybersecurity Threat Detected",
    desc: "A sophisticated cyber attack has been identified, targeting major financial institutions worldwide.",
    pubDate: "2025-02-10",
    pubName: "CyberSec Today",
    pubLogo: "https://example.com/cybersec-today-logo.png",
    sentiment: "Negative",
  },
  {
    title: "Sports Team Wins Championship",
    desc: "After a thrilling final, the underdogs secured a historic victory in the national championship.",
    pubDate: "2025-02-09",
    pubName: "Sports Weekly",
    pubLogo: "https://example.com/sports-weekly-logo.png",
    sentiment: "Positive",
  },
];